### ISSUE TITLE
旅行詳細ページでほしい情報

### ISSUE THREAD

**Issue by hand12** [Factbank/factearth#112]
旅行
- 旅行名（タイトル）
- 投稿日
- ガイド料金
- ガイド可能人数
- コメント一覧
- 見所
  - 見出し
  - 詳細説明
  - 所要時間
  - 場所
  - 画像（複数）
- 投稿したユーザ
  - 名前
  - プロフィール画像
  - お気に入りの旅先
  - 出生地

**Comment by nekoze1210** [comment]
あとはタグも必要かな？
