### ISSUE TITLE
詳細画面でリロードするとエラーになる

### ISSUE THREAD

**Issue by nekoze1210** [Factbank/factearth#64]
## 現象
https://gyazo.com/6f2c8e4037c4ffb4480032feafafee32

### 表示されたエラー文
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>tour-plans/521</Key>
<RequestId>8FB9E42C1FF42CA1</RequestId>
<HostId>
dVxVBdRBpiatBSMbdpxMOGM9c2+EQ9xgfj4nqGtM3+3EkuIVbzXPbeddsl1Ye7rArIXBO5fFY+Y=
</HostId>
</Error>
```

## 原因
S3上にはindex.htmlがエンドポイントとなっており、http://factearth-dev.comしか直でアクセスできない。
WEBサーバ（S3）側にどのリクエストも必ずindex.htmlを経由させ、vue-routerを発火させないと404になってしまう。
詳細画面のみならず、他のページでも同じ現象が起きている

## 対策
- S3にリダイレクションルールを追加する
参考:  https://medium.com/@BjornKrols/how-to-enable-history-mode-for-aws-s3-hosted-vue-applications-3bf40d51d9a7

**Comment by hand12** [comment]
ありがとう！！
これ俺も把握してて、なんでだろうって思ってたらこおいうことだったのね！
cloud front側でこれを直す処理があったから、そっちで対応した！！

**Comment by nekoze1210** [comment]
ありがとう！
解決したっぽいので、クローズします！
